# Nettoyage et merge des bases de données des communes

Merge les bases sur `codgeo` et `an`.
La base finale a une ligne par couple **(commune × année)**.

In [1]:
import pandas as pd
import os

## 1. Configuration

In [2]:
# Adapter ce chemin à votre environnement local
base_path = "/Users/margo/Documents/Margot/0.Polytechnique/Statistical-machine-learning/Projet-final/Data/"
obs_path = os.path.join(base_path, "Observatoire-territoires")

## 2. Chargement et nettoyage de chaque base

**Structure commune à tous les fichiers :**
- Lignes 0-3 : métadonnées ANCT (à ignorer)
- Ligne 4 : en-têtes réels (`codgeo`, `libgeo`, `an`, + variable)
- Lignes 5+ : données

Le nettoyage consiste à sauter les 4 premières lignes et à ne garder que les colonnes utiles.

In [3]:
def load_obs_file(filepath):
    """
    Charge un fichier Excel de l'Observatoire des territoires.
    Ignore les 4 premières lignes de métadonnées.
    Retourne un DataFrame avec codgeo (str), libgeo, an, et la variable.
    """
    df = pd.read_excel(filepath, header=4)  # La ligne 4 (index) = vrais en-têtes
    df['codgeo'] = df['codgeo'].astype(str).str.zfill(5)  # Conserve le zéro initial (ex: 01001)
    return df

In [4]:
# Chargement de toutes les bases
obs_data = {}
for file in sorted(os.listdir(obs_path)):
    if file.endswith(".xlsx"):
        name = file.replace(".xlsx", "")
        filepath = os.path.join(obs_path, file)
        obs_data[name] = load_obs_file(filepath)
        print(f"✓ {name} — {len(obs_data[name])} lignes, colonnes : {list(obs_data[name].columns)}")

✓ France_ruralité_revitalisation_FRR — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'codefrr']
✓ aah — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'benef_aah']
✓ aide_logt_ALF — 139246 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_alf']
✓ aide_logt_ALS — 139246 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'nb_als']
✓ aide_logt_APL — 139246 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_apl']
✓ aides_aux_communes — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'zonage_afr22']
✓ aire_attraction_ville — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'aav2020', 'aav2020_libgeo']
✓ alloc_APA — 201 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'benef_apa']
✓ communes_territoire_industrie — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'ti_zpp2']
✓ demandeurs_emplois_moins_25ans — 9151 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_de_25']
✓ densité_pop — 278943 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'dens_pop']
✓ finances_perequation — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'com_dot_pereq_ha']
✓ indice_vieillissement — 278943 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'ind_vieillist']
✓ logements_vacants — 69750 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_vacant_plus_2ans']
✓ médiane_revenu — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'med_disp']
✓ nb_creation_etablissement — 174375 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'etctot']
✓ nb_logements_sociaux — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'nb_rpls']
✓ nb_naissance — 244125 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'nais_an']
✓ niveau_équipement — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'nivcentr']
✓ part_ménages_au_moins_une_voiture — 104591 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_men_voit1p']
✓ part_ménages_emmenagés_2_9ans — 104591 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_men_anem0209']
✓ part_ménages_emmenagés_moins_2ans — 104591 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_men_anem2m']
✓ part_ménages_emmenagés_plus_10ans — 104591 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_men_anem_10p']
✓ part_résidences_pincipales — 278943 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_rp']
✓ part_résidences_secondaires — 278943 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'part_resid2']
✓ pauvreté — 34875 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'tx_pauv_60']
✓ pop_recensement — 278943 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'p_pop']
✓ rsa — 279000 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'alloc_rsa']
✓ taux_evolution_pop — 244125 lignes, colonnes : ['codgeo', 'libgeo', 'an', 'tx_var_pop']

## 3. Aperçu rapide de chaque base

In [5]:
for name, df in obs_data.items():
    print(f"\n=== {name} ===")
    print(f"  Dimensions : {df.shape}")
    print(f"  Années disponibles : {sorted(df['an'].dropna().unique()) if 'an' in df.columns else 'N/A'}")
    display(df.head(3))

=== France_ruralité_revitalisation_FRR ===
  Dimensions : (34875, 3)
  Années disponibles : N/A

  codgeo                   libgeo  codefrr
0  01001  L'Abergement-Clémenciat      NaN
1  01002    L'Abergement-de-Varey      NaN
2  01004        Ambérieu-en-Bugey      NaN

=== aah ===
  Dimensions : (34875, 4)
  Années disponibles : [np.int64(2021)]

  codgeo                   libgeo    an  benef_aah
0  01001  L'Abergement-Clémenciat  2021        NaN
1  01002    L'Abergement-de-Varey  2021        NaN
2  01004        Ambérieu-en-Bugey  2021      290.0

=== aide_logt_ALF ===
  Dimensions : (139246, 4)
  Années disponibles : [np.float64(2020.0), np.float64(2021.0), np.float64(2022.0), np.float64(2023.0)]

  codgeo                   libgeo      an  part_alf
0  01001  L'Abergement-Clémenciat  2020.0       3.2
1  01001  L'Abergement-Clémenciat  2021.0       0.0
2  01001  L'Abergement-Clémenciat  2022.0       0.0

=== aide_logt_ALS ===
  Dimensions : (139246, 4)
  Années disponibles : [np.float64(2020.0), np.float64(2021.0), np.float64(2022.0), np.float64(2023.0)]

  codgeo                   libgeo      an  nb_als
0  01001  L'Abergement-Clémenciat  2020.0     0.0
1  01001  L'Abergement-Clémenciat  2021.0     0.0
2  01001  L'Abergement-Clémenciat  2022.0     0.0

=== aide_logt_APL ===
  Dimensions : (139246, 4)
  Années disponibles : [np.float64(2020.0), np.float64(2021.0), np.float64(2022.0), np.float64(2023.0)]

  codgeo                   libgeo      an  part_apl
0  01001  L'Abergement-Clémenciat  2020.0       4.8
1  01001  L'Abergement-Clémenciat  2021.0       3.0
2  01001  L'Abergement-Clémenciat  2022.0       4.3

=== aides_aux_communes ===
  Dimensions : (34875, 3)
  Années disponibles : N/A

  codgeo                   libgeo zonage_afr22
0  01001  L'Abergement-Clémenciat           NC
1  01002    L'Abergement-de-Varey           NC
2  01004        Ambérieu-en-Bugey           NC

=== aire_attraction_ville ===
  Dimensions : (34875, 4)
  Années disponibles : N/A

  codgeo                   libgeo aav2020            aav2020_libgeo
0  01001  L'Abergement-Clémenciat     524  Châtillon-sur-Chalaronne
1  01002    L'Abergement-de-Varey     NaN                       NaN
2  01004        Ambérieu-en-Bugey     243         Ambérieu-en-Bugey

=== alloc_APA ===
  Dimensions : (201, 4)
  Années disponibles : [np.float64(2021.0), np.float64(2022.0)]

  codgeo libgeo      an  benef_apa
0  00001    Ain  2021.0    10625.0
1  00001    Ain  2022.0    10181.0
2  00002  Aisne  2021.0    13803.0

=== communes_territoire_industrie ===
  Dimensions : (34875, 3)
  Années disponibles : N/A

  codgeo                   libgeo ti_zpp2
0  01001  L'Abergement-Clémenciat     out
1  01002    L'Abergement-de-Varey     out
2  01004        Ambérieu-en-Bugey     out

=== demandeurs_emplois_moins_25ans ===
  Dimensions : (9151, 4)
  Années disponibles : [np.float64(1996.0), np.float64(1997.0), np.float64(1998.0), np.float64(1999.0), np.float64(2000.0), np.float64(2001.0), np.float64(2002.0), np.float64(2003.0), np.float64(2004.0), np.float64(2005.0), np.float64(2006.0), np.float64(2007.0), np.float64(2008.0), np.float64(2009.0), np.float64(2010.0), np.float64(2011.0), np.float64(2012.0), np.float64(2013.0), np.float64(2014.0), np.float64(2015.0), np.float64(2016.0), np.float64(2017.0), np.float64(2018.0), np.float64(2019.0), np.float64(2020.0), np.float64(2021.0), np.float64(2022.0), np.float64(2023.0), np.float64(2024.0), np.float64(2025.0)]

  codgeo   libgeo      an  part_de_25
0  00051  Alençon  1996.0         NaN
1  00051  Alençon  1997.0         NaN
2  00051  Alençon  1998.0         NaN

=== densité_pop ===
  Dimensions : (278943, 4)
  Années disponibles : [np.int64(1968), np.int64(1975), np.int64(1982), np.int64(1990), np.int64(1999), np.int64(2011), np.int64(2016), np.int64(2022)]

  codgeo                   libgeo    an  dens_pop
0  01001  L'Abergement-Clémenciat  1968     21.82
1  01001  L'Abergement-Clémenciat  1975     23.14
2  01001  L'Abergement-Clémenciat  1982     30.00

=== finances_perequation ===
  Dimensions : (34875, 4)
  Années disponibles : [np.int64(2025)]

  codgeo                   libgeo    an  com_dot_pereq_ha
0  01001  L'Abergement-Clémenciat  2025              44.4
1  01002    L'Abergement-de-Varey  2025              39.6
2  01004        Ambérieu-en-Bugey  2025              35.6

=== indice_vieillissement ===
  Dimensions : (278943, 4)
  Années disponibles : [np.int64(1968), np.int64(1975), np.int64(1982), np.int64(1990), np.int64(1999), np.int64(2011), np.int64(2016), np.int64(2022)]

  codgeo                   libgeo    an  ind_vieillist
0  01001  L'Abergement-Clémenciat  1968           31.0
1  01001  L'Abergement-Clémenciat  1975           24.0
2  01001  L'Abergement-Clémenciat  1982           24.0

=== logements_vacants ===
  Dimensions : (69750, 4)
  Années disponibles : [np.int64(2020), np.int64(2024)]

  codgeo                   libgeo    an  part_vacant_plus_2ans
0  01001  L'Abergement-Clémenciat  2020                    NaN
1  01001  L'Abergement-Clémenciat  2024                    NaN
2  01002    L'Abergement-de-Varey  2020                    NaN

=== médiane_revenu ===
  Dimensions : (34875, 4)
  Années disponibles : [np.int64(2021)]

  codgeo                   libgeo    an  med_disp
0  01001  L'Abergement-Clémenciat  2021   25820.0
1  01002    L'Abergement-de-Varey  2021   24480.0
2  01004        Ambérieu-en-Bugey  2021   21660.0

=== nb_creation_etablissement ===
  Dimensions : (174375, 4)
  Années disponibles : [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022)]

  codgeo                   libgeo    an  etctot
0  01001  L'Abergement-Clémenciat  2018     6.0
1  01001  L'Abergement-Clémenciat  2019     9.0
2  01001  L'Abergement-Clémenciat  2020    12.0

=== nb_logements_sociaux ===
  Dimensions : (34875, 4)
  Années disponibles : [np.float64(2023.0)]

  codgeo                   libgeo      an  nb_rpls
0  01001  L'Abergement-Clémenciat  2023.0     22.0
1  01002    L'Abergement-de-Varey     NaN      NaN
2  01004        Ambérieu-en-Bugey  2023.0   2084.0

=== nb_naissance ===
  Dimensions : (244125, 4)
  Années disponibles : ['1968-1975', '1975-1982', '1982-1990', '1990-1999', '1999-2011', '2011-2016', '2016-2022']

  codgeo                   libgeo         an  nais_an
0  01001  L'Abergement-Clémenciat  1968-1975      5.0
1  01001  L'Abergement-Clémenciat  1975-1982      4.0
2  01001  L'Abergement-Clémenciat  1982-1990      6.0

=== niveau_équipement ===
  Dimensions : (34875, 4)
  Années disponibles : [np.int64(2021)]

  codgeo                   libgeo    an  nivcentr
0  01001  L'Abergement-Clémenciat  2021       0.0
1  01002    L'Abergement-de-Varey  2021       0.0
2  01004        Ambérieu-en-Bugey  2021       3.0

=== part_ménages_au_moins_une_voiture ===
  Dimensions : (104591, 4)
  Années disponibles : [np.float64(2011.0), np.float64(2016.0), np.float64(2022.0)]

  codgeo                   libgeo      an  part_men_voit1p
0  01001  L'Abergement-Clémenciat  2011.0             95.7
1  01001  L'Abergement-Clémenciat  2016.0             94.2
2  01001  L'Abergement-Clémenciat  2022.0             97.5

=== part_ménages_emmenagés_2_9ans ===
  Dimensions : (104591, 4)
  Années disponibles : [np.float64(2011.0), np.float64(2016.0), np.float64(2022.0)]

  codgeo                   libgeo      an  part_men_anem0209
0  01001  L'Abergement-Clémenciat  2011.0               31.6
1  01001  L'Abergement-Clémenciat  2016.0               24.8
2  01001  L'Abergement-Clémenciat  2022.0               33.4

=== part_ménages_emmenagés_moins_2ans ===
  Dimensions : (104591, 4)
  Années disponibles : [np.float64(2011.0), np.float64(2016.0), np.float64(2022.0)]

  codgeo                   libgeo      an  part_men_anem2m
0  01001  L'Abergement-Clémenciat  2011.0              5.3
1  01001  L'Abergement-Clémenciat  2016.0              7.7
2  01001  L'Abergement-Clémenciat  2022.0             10.5

=== part_ménages_emmenagés_plus_10ans ===
  Dimensions : (104591, 4)
  Années disponibles : [np.float64(2011.0), np.float64(2016.0), np.float64(2022.0)]

  codgeo                   libgeo      an  part_men_anem_10p
0  01001  L'Abergement-Clémenciat  2011.0               62.5
1  01001  L'Abergement-Clémenciat  2016.0               66.1
2  01001  L'Abergement-Clémenciat  2022.0               56.4

=== part_résidences_pincipales ===
  Dimensions : (278943, 4)
  Années disponibles : [np.int64(1968), np.int64(1975), np.int64(1982), np.int64(1990), np.int64(1999), np.int64(2011), np.int64(2016), np.int64(2022)]

  codgeo                   libgeo    an  part_rp
0  01001  L'Abergement-Clémenciat  1968     73.9
1  01001  L'Abergement-Clémenciat  1975     72.6
2  01001  L'Abergement-Clémenciat  1982     78.4

=== part_résidences_secondaires ===
  Dimensions : (278943, 4)
  Années disponibles : [np.int64(1968), np.int64(1975), np.int64(1982), np.int64(1990), np.int64(1999), np.int64(2011), np.int64(2016), np.int64(2022)]

  codgeo                   libgeo    an  part_resid2
0  01001  L'Abergement-Clémenciat  1968         10.6
1  01001  L'Abergement-Clémenciat  1975         14.9
2  01001  L'Abergement-Clémenciat  1982         12.5

=== pauvreté ===
  Dimensions : (34875, 4)
  Années disponibles : [np.int64(2021)]

  codgeo                   libgeo    an  tx_pauv_60
0  01001  L'Abergement-Clémenciat  2021         NaN
1  01002    L'Abergement-de-Varey  2021         NaN
2  01004        Ambérieu-en-Bugey  2021        17.0

=== pop_recensement ===
  Dimensions : (278943, 4)
  Années disponibles : [np.int64(1968), np.int64(1975), np.int64(1982), np.int64(1990), np.int64(1999), np.int64(2011), np.int64(2016), np.int64(2022)]

  codgeo                   libgeo    an  p_pop
0  01001  L'Abergement-Clémenciat  1968  347.0
1  01001  L'Abergement-Clémenciat  1975  368.0
2  01001  L'Abergement-Clémenciat  1982  477.0

=== rsa ===
  Dimensions : (279000, 4)
  Années disponibles : [np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023)]

  codgeo                   libgeo    an  alloc_rsa
0  01001  L'Abergement-Clémenciat  2016        7.0
1  01001  L'Abergement-Clémenciat  2017        NaN
2  01001  L'Abergement-Clémenciat  2018        NaN

=== taux_evolution_pop ===
  Dimensions : (244125, 4)
  Années disponibles : ['1968-1975', '1975-1982', '1982-1990', '1990-1999', '1999-2011', '2011-2016', '2016-2022']

  codgeo                   libgeo         an  tx_var_pop
0  01001  L'Abergement-Clémenciat  1968-1975        0.84
1  01001  L'Abergement-Clémenciat  1975-1982        3.78
2  01001  L'Abergement-Clémenciat  1982-1990        2.45

# 4. Séparation des bases à l'échelle communale et à l'échelle départementale
Il y a des bases de données qui ne sont pas à l'échelle de la commune mais du département. Une solution : attribuer la même valeur aux communes du même département. Une autre plus radicale, supprimer cette base de données. 

On pourra, après avoir pris une décision, supprimer le code chunk suivant (pas très utile)

In [6]:
# Identifier les bases par niveau géographique
bases_commune = {}
bases_dept = {}

for name, df in obs_data.items():
    # Les codgeo départementaux ont 2 caractères (avant zfill(5) → '00001' pour dept '1')
    # On détecte en regardant la longueur des codgeo AVANT le zfill
    raw = pd.read_excel(os.path.join(obs_path, [f for f in os.listdir(obs_path) if name in f][0]), header=4)
    raw_codgeo = raw['codgeo'].astype(str).str.strip()
    max_len = raw_codgeo.dropna().apply(len).max()
    
    if max_len <= 3:  # Département ou région
        bases_dept[name] = df
        print(f"[DÉPARTEMENT] {name}")
    else:
        bases_commune[name] = df
        print(f"[COMMUNE]     {name}")

[COMMUNE]     France_ruralité_revitalisation_FRR
[COMMUNE]     aah
[COMMUNE]     aide_logt_ALF
[COMMUNE]     aide_logt_ALS
[COMMUNE]     aide_logt_APL
[COMMUNE]     aides_aux_communes
[COMMUNE]     aire_attraction_ville
[DÉPARTEMENT] alloc_APA
[COMMUNE]     communes_territoire_industrie
[COMMUNE]     demandeurs_emplois_moins_25ans
[COMMUNE]     densité_pop
[COMMUNE]     finances_perequation
[COMMUNE]     indice_vieillissement
[COMMUNE]     logements_vacants
[COMMUNE]     médiane_revenu
[COMMUNE]     nb_creation_etablissement
[COMMUNE]     nb_logements_sociaux
[COMMUNE]     nb_naissance
[COMMUNE]     niveau_équipement
[COMMUNE]     part_ménages_au_moins_une_voiture
[COMMUNE]     part_ménages_emmenagés_2_9ans
[COMMUNE]     part_ménages_emmenagés_moins_2ans
[COMMUNE]     part_ménages_emmenagés_plus_10ans
[COMMUNE]     part_résidences_pincipales
[COMMUNE]     part_résidences_secondaires
[COMMUNE]     pauvreté
[COMMUNE]     pop_recensement
[COMMUNE]     rsa
[COMMUNE]     taux_evolution_pop

## 5. Séparation des bases sans colonne `an` (données transversales)
Même dilemme : est-ce qu'on rend constant à travers le temps ces variables ? Ou tout simplement on les supprime ?

A faire : regarder pour chaque base de données quelles sont les années présentes

In [7]:
# Certaines bases n'ont pas de dimension temporelle (ex: FRR)
bases_avec_an = {}
bases_sans_an = {}

for name, df in bases_commune.items():
    if 'an' in df.columns and df['an'].notna().any():
        bases_avec_an[name] = df
    else:
        bases_sans_an[name] = df
        print(f"[SANS ANNÉE] {name} — sera jointe sur codgeo uniquement")

print(f"\nBases avec année : {len(bases_avec_an)}")
print(f"Bases sans année : {len(bases_sans_an)}")

[SANS ANNÉE] France_ruralité_revitalisation_FRR — sera jointe sur codgeo uniquement
[SANS ANNÉE] aides_aux_communes — sera jointe sur codgeo uniquement
[SANS ANNÉE] aire_attraction_ville — sera jointe sur codgeo uniquement
[SANS ANNÉE] communes_territoire_industrie — sera jointe sur codgeo uniquement

Bases avec année : 24
Bases sans année : 4

## 6. Construction de la base finale (commune × année)

**Stratégie :** merge progressif sur `codgeo` + `an` avec `outer join` pour conserver toutes les communes et années présentes dans au moins une base.

In [ ]:
def get_variable_cols(df):
    """Retourne les colonnes qui ne sont pas codgeo, libgeo, an."""
    return [c for c in df.columns if c not in ['codgeo', 'libgeo', 'an']]

def load_obs_file(filepath):
    df = pd.read_excel(filepath, header=4)
    # Nettoyage du Code INSEE
    df['codgeo'] = df['codgeo'].astype(str).str.zfill(5)
    

    if 'an' in df.columns:
        # On supprime les lignes où l'année est vide avant conversion
        df = df.dropna(subset=['an']) 
        # On convertit en entier pour éviter les "2022.0"
        df['an'] = df['an'].astype(int) 
    
    return df

# Initialisation avec la première base ayant une colonne 'an'
base_names = list(bases_avec_an.keys())
merged = bases_avec_an[base_names[0]][['codgeo', 'libgeo', 'an'] + get_variable_cols(bases_avec_an[base_names[0]])].copy()
print(f"Base initiale : {base_names[0]} — {merged.shape}")

# Merge progressif
for name in base_names[1:]:
    df = bases_avec_an[name]
    var_cols = get_variable_cols(df)
    df_to_merge = df[['codgeo', 'an'] + var_cols].copy()
    
    merged = merged.merge(df_to_merge, on=['codgeo', 'an'], how='outer')
    
    # Récupérer libgeo si manquant
    if 'libgeo' not in merged.columns:
        merged = merged.merge(df[['codgeo', 'libgeo']].drop_duplicates(), on='codgeo', how='left')
    
    print(f"  + {name} → {merged.shape}")

print(f"\nBase mergée (avec années) : {merged.shape}")

Base initiale : aah — (34875, 4)
  + aide_logt_ALF → (139315, 5)
  + aide_logt_ALS → (139315, 6)
  + aide_logt_APL → (139315, 7)
  + demandeurs_emplois_moins_25ans → (147918, 8)
  + densité_pop → (391651, 9)
  + finances_perequation → (426389, 10)
  + indice_vieillissement → (426389, 11)
  + logements_vacants → (461187, 12)
  + médiane_revenu → (461187, 13)
  + nb_creation_etablissement → (530663, 14)
  + nb_logements_sociaux → (548704, 15)

ValueError: You are trying to merge on float64 and object columns for key 'an'. If you wish to proceed you should use pd.concat

In [ ]:
# Ajout des bases sans colonne 'an' (jointure sur codgeo uniquement)
for name, df in bases_sans_an.items():
    var_cols = get_variable_cols(df)
    df_to_merge = df[['codgeo'] + var_cols].drop_duplicates('codgeo')
    merged = merged.merge(df_to_merge, on='codgeo', how='left')
    print(f"  + {name} (sans an) → {merged.shape}")

In [ ]:
# Nettoyage final : réorganiser les colonnes
id_cols = ['codgeo', 'libgeo', 'an']
other_cols = [c for c in merged.columns if c not in id_cols]
merged = merged[id_cols + other_cols]

# Trier par commune puis année
merged = merged.sort_values(['codgeo', 'an']).reset_index(drop=True)

print(f"Base finale : {merged.shape[0]} lignes × {merged.shape[1]} colonnes")
merged.head(10)

## 7. Informations sur la base finale

In [ ]:
print("=== Résumé de la base finale ===")
print(f"Nombre de communes uniques : {merged['codgeo'].nunique()}")
print(f"Années couvertes : {sorted(merged['an'].dropna().unique())}")
print(f"\nVariables disponibles ({len(other_cols)}) :")
for col in other_cols:
    n_non_null = merged[col].notna().sum()
    pct = 100 * n_non_null / len(merged)
    print(f"  {col:<35} {n_non_null:>8} valeurs non-nulles ({pct:.1f}%)")

In [ ]:
merged.info()

## 8. Export de la base finale

In [ ]:
output_path = os.path.join(base_path, "base_finale_communes.csv")
merged.to_csv(output_path, index=False, encoding='utf-8-sig')  # utf-8-sig pour les accents sous Excel
print(f"✓ Base exportée : {output_path}")

# Export également en parquet pour des accès rapides
output_parquet = os.path.join(base_path, "base_finale_communes.parquet")
merged.to_parquet(output_parquet, index=False)
print(f"✓ Base exportée : {output_parquet}")

## 9. (Optionnel) Jointure avec la base département

La base `minimum_vieillesse` est au niveau département. On peut l'ajouter en faisant correspondre les 2 premiers caractères du `codgeo` commune.

In [ ]:
if bases_dept:
    merged['codgeo_dept'] = merged['codgeo'].str[:2]
    
    for name, df in bases_dept.items():
        var_cols = get_variable_cols(df)
        df_dept = df[['codgeo', 'an'] + var_cols].copy()
        df_dept = df_dept.rename(columns={'codgeo': 'codgeo_dept'})
        df_dept['codgeo_dept'] = df_dept['codgeo_dept'].astype(str).str.zfill(2)
        
        if 'an' in df_dept.columns:
            merged = merged.merge(df_dept, on=['codgeo_dept', 'an'], how='left')
        else:
            merged = merged.merge(df_dept.drop_duplicates('codgeo_dept'), on='codgeo_dept', how='left')
        
        print(f"  + {name} (département) → {merged.shape}")
    
    merged = merged.drop(columns=['codgeo_dept'])
    print(f"\nBase finale avec données département : {merged.shape}")
    display(merged.head())